### PR TITLE
food added

### PR DESCRIPTION
**Pull request by pracagra**

### CODE REVIEW

**Comment by Ashu-4u** [comment]
@pracagra Listen "chocos " is okay, but its not "Aaloo Parathe" its actually "Aaloo Paramnthe". So please update it as soon as possible.

**Comment by pracagra** [comment]
@Ashu-4u ..it seems to be ok..you please google it :)

**Comment by Ashu-4u** [comment]
@pracagra It is not at all okay. Please watch this video. 
https://www.youtube.com/watch?v=J6S5PQHvYg8

Hence, Google proved it. Please be fast.

**Comment by pracagra** [comment]
@Ashu-4u Right now i am very busy..will catch you soon..

**Comment by Ashu-4u** [comment]
@pracagra Same 2 Same. I'm also busy. But you should find time for important works, or else you will be fired by our PO..

**Pull request merged**
